### ISSUE TITLE
Images are extremely low res on mobile

### ISSUE THREAD

**Issue by aeneasr** [ory/web#226] opened 2021-06-04 17:00 UTC
**Describe the bug**

Safari

![3DF1327C-85F7-4A8B-AC07-F98D21EF7D21](https://user-images.githubusercontent.com/3372410/120837271-ca854600-c566-11eb-8780-f3ad0e337b25.png)

Chrome

![686207C5-5A7B-41A2-992A-F299197C690D](https://user-images.githubusercontent.com/3372410/120837397-ee488c00-c566-11eb-9f4e-3b5f1804c0a0.png)

Tested on iPhone 12 Safari and Chrome

**Comment by Benehiko** [comment] 2021-06-08 14:09
I was not able to reproduce - using Android 10
Chrome 91

![Screenshot_20210608-160818_Chrome.jpg](https://user-images.githubusercontent.com/18033717/121200091-c3667c80-c873-11eb-9d12-0ed6944468b6.jpg)

**Comment by aeneasr** [comment] 2021-06-08 14:34
I think this is a dupe of #225

**Comment by vinckr** [comment] 2021-06-17 10:41
Also looks good on my Android 4.4.4. with super old Chrome and some weird Samsung Browser. 

So I guess this is specific to Safari mobile. 
I will see to do some testing with other browsers as well.

**Comment by vinckr** [comment] 2021-07-05 12:17
Fixed in https://github.com/ory/web/pull/269

**Closed** 2021-07-05 12:16 UTC
