### ISSUE TITLE
Missing link for distributed tracing in Kratos guides

### ISSUE THREAD

**Issue by ganapathi004** [ory/web#260] opened 2021-06-27 13:48 UTC
On this page https://www.ory.sh/docs/ecosystem/projects/, clicking `Open Source Documentation > Ory Kratos > Guides`, there is a link for `Distributed Tracing`, which gives a 404 in a new tab when clicked. The Kratos repository has a doc on tracing available - https://github.com/ory/kratos/blob/master/docs/docs/guides/tracing.mdx. This file - https://github.com/ory/kratos/blob/master/docs/sidebar.json contains an entry for `guides/tracing`.

I couldn't figure out where to correct this. If someone can guide me, I want to fix this.

**Comment by vinckr** [comment] 2021-07-22 13:56
should be fixed now! 
could not reproduce.

**Closed by vinckr** 2021-07-22 13:56 UTC
